### ISSUE TITLE
plugin-sh: Ignored unknown option warning

### ISSUE THREAD

**Issue by lexusdrumgold** [rx-ts/prettier#109]
## Bug Description

After running either of the following commands: **`prettier --write .`** or **`prettier --check .`**,  my logs are filled with `Ignored unknown option` warnings. My shell files (and a `.gitconfig` file) are still being formatted, however.

 **Sample output from running `prettier --write .`**

```zsh
[warn] Ignored unknown option { functionNextLine: true }.
[warn] Ignored unknown option { indent: 4 }.
[warn] Ignored unknown option { keepComments: true }.
[warn] Ignored unknown option { keepPadding: false }.
[warn] Ignored unknown option { spaceRedirects: true }.
[warn] Ignored unknown option { switchCaseIndent: true }.
[warn] Ignored unknown option { variant: 0 }.
scripts/prepublish.sh 31ms
scripts/ts/debug.ts 26ms
scripts/ts/fix-node-module-paths.ts 69ms
scripts/ts/release.ts 258ms
[warn] Ignored unknown option { functionNextLine: true }.
[warn] Ignored unknown option { indent: 4 }.
[warn] Ignored unknown option { keepComments: true }.
[warn] Ignored unknown option { keepPadding: false }.
[warn] Ignored unknown option { spaceRedirects: true }.
[warn] Ignored unknown option { switchCaseIndent: true }.
[warn] Ignored unknown option { variant: 0 }.
scripts/zsh-install.sh 79ms
```

## Steps to reproduce

1. Clone the [repro repository](https://github.com/flex-development/ts-pkg/tree/383f6e9399623a10340b0c7c9afd4945e171c232)
2. Remove `@flex-development/exceptions` and `@flex-development/tutils` from `dependencies`
3. Run `yarn` in the project root
4. Run `yarn check:format` or `yarn fix:format`
5. See error (extraneous warning logs) 

## Expected behavior

There should be no warnings in the console.

## Relevant screenshots

 **Screenshot of logs after running `prettier --check .`**

![Screen Shot 2021-06-09 at 10 05 05 PM](https://user-images.githubusercontent.com/20430108/121453376-14a76680-c96f-11eb-936e-e33796cf083c.png)

## Environment

- `prettier` version: `v2.3.1`
- `prettier-plugin-sh` version: `v0.6.1`

## Possible solution

Unsure of a possible solutions.

## Additional context

- Another user had this issue, but their problem seemed to disappear. See issue #106 
- In the screenshot above, you can see the second Prettier configuration I tried. The first looked like this:

  ```js
  module.exports = {
    arrowParens: 'avoid',
    bracketSpacing: true,
    functionNextLine: true,
    htmlWhitespaceSensitivity: 'css',
    indent: 4,
    jsxBracketSameLine: false,
    jsxSingleQuote: true,
    keepComments: true,
    keepPadding: false,
    parser: 'sh',
    printWidth: 80,
    proseWrap: 'always',
    quoteProps: 'as-needed',
    semi: false,
    singleQuote: true,
    spaceRedirects: true,
    switchCaseIndent: true,
    tabWidth: 2,
    trailingComma: 'none',
    variant: 0
  }
  ```

**Comment by JounQin** [comment]
I think this is a prettier usage question, you are passing `sh` specific options for all files including `.ts` files which is not related to the plugin.

Personally I think the warning strategy is bad.

**Comment by lexusdrumgold** [comment]
> I think this is a prettier usage question, you are passing `sh` specific options for all files including `.ts` files which is not related to the plugin.
> 
> Personally I think the warning strategy is bad.
> 
> If you think this is unexpected, please report to prettier instead.

@JounQin 

This issue should be re-opened. I don’t think you interpreted it correctly. The screenshot I included shows my latest Prettier configuration (see above: “In the screenshot above, you can see the second Prettier configuration I tried”). 

In the screenshot, you can see I set `overrides[0].files` to `*.sh`, thus, to my understanding, only passing plugin options to `sh` files. The code snippet you’re alluding to was included for context.

**Comment by JounQin** [comment]
It's clear that a plugin has no control how prettier's warning, so please raise issue on their side.

**Comment by JounQin** [comment]
prettier-plugin-sh@0.7.0 released

I tried your reproduction, it's working now.

**Comment by lexusdrumgold** [comment]
@JounQin 

Thanks so much for the quick response and I appreciate you tackling this issue. I’ll install the latest version and drop a comment later just to confirm.

**Comment by lexusdrumgold** [comment]
@JounQin everything works as expected! thanks again!
