### ISSUE TITLE
sh - false postive on closing quote

### ISSUE THREAD

**Issue by tomdavidson** [rx-ts/prettier#133]
Hello, `prettier-plugin-sh` seems to be giving me a false positive:

```
lolaus.sh
[error] lolaus.sh: SyntaxError: reached EOF without closing quote "
[error]   186 | }
[error]   187 |
[error] > 188 | main "$@"
[error]       |         ^
[error]   189 |
```

Here is a [gist of the script](https://gist.github.com/tomdavidson/cda2ad09105f2a80dd949b7957ca3a6a). I can not found a missing quote or bracket. The script runs fine and passes shellcheck, maybe there is still an error in the script but it seems there is potential it is in the plug-in.

Any pointers? And thanks.

**Comment by JounQin** [comment]
Sorry for the delay first, I tried [`mvdan-sh`](https://github.com/mvdan/sh)'s latest go tool, it is working correctly.

But its js module is outdated, let wait for the original author first.
