### ISSUE TITLE
prettier-plugin-sh v0.8.0 broken

### ISSUE THREAD

**Issue by zdm** [rx-ts/prettier#135]
After updated `prettier-plugin-sh` to 0.8.0 it not works anymore. 
Dies with the error `Couldn't resolve parser sh`

**Comment by zdm** [comment]
Also, do you know, that all package versions below 1.0.0 are treats by npm as pre-release versions and doesn't updated as regular releases. 
This is usually not, what users are expected. First public version should be 1.0.0.

**Comment by JounQin** [comment]
Can you provide a runnable production?

**Comment by JounQin** [comment]
`^0.8.0` means breaking changes from `^0.7.1`, it is semver version.

**Comment by zdm** [comment]
This is incorrect.
In semver breaking change must increase major version 1.0.0 -> 2.0.0 -> etc...
Npm and other software will not recognize your brealing changes and will update package incorrectly.
Look at the specification, pls.

**Comment by JounQin** [comment]
No, versions under `1.0.0` are not stable, so `0.7` -> `0.8` could be breaking change. That why `^0.7.0` will not resolve `0.8.0`.

**Comment by JounQin** [comment]
> Look at the specification, pls.

You should read it more carefully by yourself.

https://semver.org/#spec-item-4

**Comment by JounQin** [comment]
Besides, `^0.8.1` has been released which fixed the cjs entry issue. `tsc -b` outputs commonjs with `exports.default = ShPlugin` which is incorrect, it has been bundled by `rollup` again with `module.exports = ShPlugin`, so it should just work as expected now.

**Comment by zdm** [comment]
Yes, I see, not it works. Thank you.

**Comment by JounQin** [comment]
> Yes, I see, not it works.

As a non-native English speaker, I don't understand whether it works for you or not. If it doesn't, please provide a runnable reproduction, thanks.

**Comment by zdm** [comment]
It was a typo, sorry.
I mean "now it works".
