### ISSUE TITLE
prettier-sh broken

### ISSUE THREAD

**Issue by Gadgetroch** [rx-ts/prettier#136]
Prettier Version: 2.4.1
Running Prettier via: CLI
Runtime: NodeJS v12.22.5
Operating System: Debian 11
Prettier plugins (if any): SH
Steps to reproduce:

prettier -w file.sh

Expected behavior:

Formatting file

Actual behavior:

[error] No parser could be inferred for file: file.sh

prettier-plugin-sh installed.

**Comment by JounQin** [comment]
Please provide a runnable reproduction.
