### ISSUE TITLE
[prettier-plugin-sql] How to configure options

### ISSUE THREAD

**Issue by 6temes** [rx-ts/prettier#143]
Hi,

I just found this library, and it seems a great addition to the Prettier ecosystem!

I am having trouble using it, though, because the default configuration is meant for MySQL, and I am not sure how to pass the options to the plugin. It does not seem to be reading them from `.prettierrc.yml`.

Thanks!

**Comment by JounQin** [comment]
> It does not seem to be reading them from .prettierrc.yml

@6temes Can you provide a minimal runnable reproduction? It should just work.

**Comment by 6temes** [comment]
@JounQin  

Sorry. I am afraid that there was a PEBKAC. The config works ok. Sorry about that.

For reference, this is my current config:

```
# In .prettierrc.yml

endOfLine: lf
printWidth: 100
semi: false
singleQuote: true
trailingComma: all
rubySingleQuote: true
rubyToProc: true

formatter: sql-formatter
language: postgresql
uppercase: true
linesBetweenQueries: 2
```

I will close the issue.

**Comment by PeterlitsZo** [comment]
I have the same question. Can we add a simple example for it?

**Comment by PeterlitsZo** [comment]
I am not sure that the option for this plugin should put at the root of rc file.

**Comment by JounQin** [comment]
PR welcome, you can always put the options at the root level or [`overrides`](https://prettier.io/docs/en/configuration.html#configuration-overrides) block.
