### ISSUE TITLE
add prettier-plugin topic to the repository

### ISSUE THREAD

**Issue by ssbarnea** [rx-ts/prettier#145]
At this moment this plugin is missing any github topics, preventing from making it discoverable on https://github.com/topics/prettier-plugin

Just go to repository home, and use the right sidebar to add `prettier-plugin` topic to it.

That is more important as there is another https://github.com/azz/prettier-plugin-bash which has that topic, but seems to have considerably less stars.

While this repository seems to be more popular and recently updated, I found that its main page is offline... https://prettier.vercel.app/ returning `[object Object]`

**Comment by JounQin** [comment]
Thanks for report, it has been fixed.
