### ISSUE TITLE
[prettier-plugin-sh] Fail with error since 0.9 and 0.10 on specific shell script

### ISSUE THREAD

**Issue by ath0mas** [rx-ts/prettier#162]
Running prettier with `write` or `check` on one of my shell scripts started to fail since 0.9 and 0.10 ; was ok with 0.8.2.

```
prettier --write given-script.sh
prettier --check given-script.sh
```

... this script has 215 lines, some blank, and trying to remove few random lines seems to get back to no error (6 or more, it depends on the lines, even basic `echo`s).

It is still fine with all my other scripts and Dockerfiles.

I can not share this file as it is close source.

(Windows 10, Node 17.8.0, npm 8.5.5)

<details open>
<summary>with <b>0.10.0</b> and <b>0.9.1</b></summary>
<br>
<pre>
given-script.sh[error] given-script.sh: Error: total length of command line and environment variables exceeds limit
[error]     at globalThis.Go.run (file:///C:/Users/myuser/AppData/Roaming/npm/node_modules/prettier-plugin-sh/node_modules/sh-syntax/vendors/wasm_exec.js:524:11)
[error]     at file:///C:/Users/myuser/AppData/Roaming/npm/node_modules/prettier-plugin-sh/node_modules/sh-syntax/lib/processor.js:60:22
[error]     at Generator.next (<anonymous>)
[error]     at fulfilled (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier-plugin-sh\node_modules\tslib\tslib.js:114:62)
</pre>
</details>

<details>
<summary>with <b>0.9.0</b></summary>
<br>
<pre>
given-script.sh[error] given-script.sh: TypeError: Cannot read properties of undefined (reading 'col')
[error]     at Object.print (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier-plugin-sh\lib\index.cjs:473:35)
[error]     at callPluginPrintFunction (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\index.js:8447:26)
[error]     at mainPrintInternal (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\index.js:8396:22)
[error]     at mainPrint (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\index.js:8383:18)
[error]     at printAstToDoc (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\index.js:8375:18)
[error]     at coreFormat (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\index.js:8680:20)
[error]     at formatWithCursor2 (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\index.js:8864:18)
[error]     at Object.formatWithCursor (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\index.js:39174:12)
[error]     at format (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\cli.js:12043:24)
[error]     at formatFiles2 (C:\Users\myuser\AppData\Roaming\npm\node_modules\prettier\cli.js:12122:20)
</pre>
</details>

**Comment by ath0mas** [comment]
Fine I looked for Shell repositories here on GitHub and found some scripts to reproduce:
```
git clone https://github.com/nvm-sh/nvm
cd nvm/
prettier --check "**/*.sh"
```
- Failing for **install.sh** and **nvm.sh** with the exact same error.
- OK for the 3 other scripts : reformating _rename_test.sh_ and _test\common.sh_, and already fine for _update_test_mocks.sh_.

I have not found what is causing this issue, what arbitrary changes are solving it, or how to really set a minimal reproduction.

**Comment by JounQin** [comment]
OK, I'll give it a try when I'm free, thanks for reporting.

**Comment by JounQin** [comment]
https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/data.go#L2458
https://github.com/golang/go/blob/master/misc/wasm/wasm_exec.js#L522-L525

I need to find whether this is any workaround...

**Comment by JounQin** [comment]
@ath0mas Please try 0.10.1

**Comment by ath0mas** [comment]
@JounQin no more error using v0.10.1. Thanks!
