### ISSUE TITLE
Copyright Issue

### ISSUE THREAD

**Issue by shellscape** [rx-ts/prettier#171]
Hey. The code here https://github.com/rx-ts/prettier/tree/master/packages/pkg is a clear and obvious derivation of my work here https://github.com/shellscape/prettier-plugin-package. 

The MPL-2.0 License clearly states you must retain copyright notice, and you must notify the author (me) of any derivations. Additionally, this clause appears in all source files:

```
 Copyright © 2019 Andrew Powell
  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.
  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of this Source Code Form.
```

That means, even though you've refactored the code, you still need to include that header.

**Comment by shellscape** [comment]
This is a follow up on #42. I gave it some time to see if the code would be updated appropriately before opening a new issue.

**Comment by JounQin** [comment]
Added in https://github.com/rx-ts/prettier/commit/d831c8ae6ba59cd758293e83941276c66cc4efce#diff-6d18b772b23814d11392c0447c09d378fc4e910947503dbe43a1c4b08a667833

**Comment by JounQin** [comment]
@shellscape Do you that follows your request?

**Comment by shellscape** [comment]
Yes, thank you.
