### ISSUE TITLE
Can’t prettify .gitignore file

### ISSUE THREAD

**Issue by jlarmstrongiv** [rx-ts/prettier#176]
Thank you for creating this awesome plugin!  Works for the most part, but fails when a .gitignore file contains parenthesis:

```gitignore
## Build tool auxiliary files:
*.fdb_latexmk
*.synctex
*.synctex(busy)
*.synctex.gz
*.synctex.gz(busy)
*.pdfsync
```

Errors:
```
[error] .gitignore: SyntaxError: "foo(" must be followed by )
[error]   353 | *.fdb_latexmk
[error]   354 | *.synctex
[error] > 355 | *.synctex(busy)
[error]       | ^
[error]   356 | *.synctex.gz
[error]   357 | *.synctex.gz(busy)
[error]   358 | *.pdfsync
```

```
[error] .gitignore: SyntaxError: a command can only contain words and redirects; encountered )
[error]   353 | *.fdb_latexmk
[error]   354 | *.synctex
[error] > 355 | *.synctex*busy)
[error]       |               ^
[error]   356 | *.synctex.gz
[error]   357 | *.synctex.gz*busy)
[error]   358 | *.pdfsync
```

Related https://github.com/rx-ts/prettier/issues/175

**Comment by JounQin** [comment]
Basically other files instead of shellscript are not supported by https://github.com/mvdan/sh, they can be used in a `simple` format. If you found it is not working, then it means `mvdan-sh` does not support to parse them as shellscript, sorry.

**Comment by JounQin** [comment]
It you have more question, feel free to comment.
