### ISSUE TITLE
Configurable sorting / key ordering?

### ISSUE THREAD

**Issue by tunnckoCore** [rx-ts/prettier#4]
Can we pass custom options to plugins? For example, we can allow passing `options.keyOrder` which if preset it will be used instead of [the `primary`](https://github.com/rx-ts/prettier/blob/master/packages/pkg/src/rules/sort.ts#L4)

**Comment by JounQin** [comment]
Yeah, of course it would make sense, do you like to make a PR?

**Comment by JounQin** [comment]
I just face a sorting problem for a vscode plugin project, so it would great to provide `preset` and `customOrders` options.

**Comment by tunnckoCore** [comment]
We can use [sort-package-json](https://github.com/keithamus/sort-package-json) which allows passing custom `sortOrder` option.

As about presets, would be cool, yea. But I'm still not sure, how we can pass options to the plugins inside prettier config? Is it like it's in babel and the others?

```js
module.exports = {
  plugins: [
    ['plugin-', { sortOrder }],
  ],
};
```

**Comment by tunnckoCore** [comment]
Ooooh, it's through the `overrides`. Yeah. Cool.

**Comment by JounQin** [comment]
> We can use [sort-package-json](https://github.com/keithamus/sort-package-json) which allows passing custom `sortOrder` option.

Sorry I personally don't like its default sort and do not want to add unnecessary dependency for such simple plugin either(it could be used in browser).

It is cool to custom the order, but it's `opinionated` by default as the description in README.

> Top-level keys are sorted according to a style commonly seen in the packages of [@JounQin](https://github.com/JounQin), [@1stG](https://github.com/1stG) and [@RxTS](https://github.com/rx-ts).

**Comment by JounQin** [comment]
I'm closing this issue, if you still want this, post a PR instead.😀
