### ISSUE TITLE
Please read the MPL-2.0 LICENSE

### ISSUE THREAD

**Issue by shellscape** [rx-ts/prettier#42]
Hey there. The MPL is not MIT - one cannot silently fork or copy and create derived content without notification - and it's for that reason that I chose MPL-2.0 for [`prettier-plugin-package`](https://github.com/shellscape/prettier-plugin-package).

Here's a great summary of MPL and how derived works have to be handled: https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)

> All modified files containing MPL'd code must be disclosed under the MPL.

Of note:

> 3.4. Notices
> 
> You may not remove or alter the substance of any license notices
> (including copyright notices, patent notices, disclaimers of warranty,
> or limitations of liability) contained within the Source Code Form of
> the Covered Software, except that You may alter any license notices to
> the extent required to remedy known factual inaccuracies.

What's a real bummer here is that you've taken my source code, removed all of the licenses, retained most of the code structure, and simply converted it to TypeScript (in many cases, not modifying the code at all).

I welcome derived works and wholesale modification to my work, but I do ask that you retain my copyright notices in files that still retain my code. Given that the README still shares original elements of my package and that the commit log references my package as the basis for your new package, I would also greatly appreciate an attribution section in the README that points back to my package. It's the right thing to do.

**Comment by JounQin** [comment]
Sorry about this, I didn't notice about this issue for a long time.

Sorry again I didn't read carefully about the LICENSE file and as a non-native English user, I didn't quite understand the LICENSE content correctly, I'll raise a PR immediately to update README about your copyright and ask for your review.

Thanks for your original great work.

**Comment by shellscape** [comment]
Thank you for the additions to the readme.
