### ISSUE TITLE
[sh-0.3.1] no lib dir?

### ISSUE THREAD

**Issue by fjc0k** [rx-ts/prettier#79]
0.3.0:

https://unpkg.com/browse/prettier-plugin-sh@0.3.0/

![image](https://user-images.githubusercontent.com/13151189/79190255-64b39780-7e56-11ea-8171-35b8d4f242f0.png)

0.3.1:

https://unpkg.com/browse/prettier-plugin-sh@0.3.1/

![image](https://user-images.githubusercontent.com/13151189/79190276-75fca400-7e56-11ea-850d-f1d10fe29637.png)

**Comment by JounQin** [comment]
@fjc0k Sorry about this, it should be fixed in [v0.3.2](https://unpkg.com/browse/prettier-plugin-sh@0.3.2/).
