### ISSUE TITLE
Feature Request: match shebang lines

### ISSUE THREAD

**Issue by ahawkins** [rx-ts/prettier#90]
This seems possible according to this comment: https://github.com/prettier/prettier/issues/4774#issuecomment-655401403. This will make extensionless shell programs work out of the box with prettier.

It looks like adding an `interpreters` entry to the `languages` objects (reference https://github.com/prettier/prettier/blob/ba500e22f9001107dd9150629687df878e02b1f4/src/main/options.js#L185-L190). Also the languages would require a new `since` property to pass the previous filter.

**Comment by JounQin** [comment]
Will implement it in recent days.

**Comment by JounQin** [comment]
@ahawkins Please try `prettier-plugin-sh@0.5.0`, it should just work.
