### ISSUE TITLE
Docker-Compose Plugin

### ISSUE THREAD

**Issue by flyshek** [rx-ts/prettier#91]
I'm wondering about writing `docker-compose` plugin which will work in a similar way, how your `pkg` plugin works, I think building a next repository for a plugin is a bit no sense thing, you have cool monorepo to which I could actually contribute. @rx-ts what do you think?

**Comment by JounQin** [comment]
Sorry I didn't notice your issue for a few weeks.

It seems great, welcome to PR, once accepted, I'd like you to be a collaborator.

Thanks for your interest.

**Comment by ZiQiLN** [comment]
I'll start slowly writing that thing, actually I just have keys which should be used for sorting. That's isn't that hard I think just parse YAML to JSON and then sort keys using scripts, it should be ready for next week I think.
