### ISSUE TITLE
Visual Studio Code Support?

### ISSUE THREAD

**Issue by creepinson** [rx-ts/prettier#94]
I keep getting 
![image](https://user-images.githubusercontent.com/11761863/90342291-e01b8600-dfbb-11ea-8b37-630b2611a640.png)
this error, and i cant select prettier as a formatter for shell scripts even though it works in the cli. Not sure waht to do here.

**Comment by JounQin** [comment]
Thanks for reporting, but I can't reproduce it, and it seems beyond our control, maybe you should post an issue to [prettier-vscode](https://github.com/prettier/prettier-vscode).

**Comment by felipecrs** [comment]
For reference, I was able to make it work with:

```jsonc
// .vscode/settings.json
{
   "prettier.documentSelectors": ["**/*.sh"],
   "[shellscript]": {
     "editor.defaultFormatter": "esbenp.prettier-vscode",
     "editor.formatOnSave": true
   }
}
```

Ideally the VS Code extension should automatically discover such files, but not even the CLI does (#281).

**Comment by stephenlevitt** [comment]
> For reference, I was able to make it work with:
> 
> // .vscode/settings.json
> {
>    "prettier.documentSelectors": ["**/*.sh"],
>    "[shellscript]": {
>      "editor.defaultFormatter": "esbenp.prettier-vscode",
>      "editor.formatOnSave": true
>    }
> }
> 
> Ideally the VS Code extension should automatically discover such files, but not even the CLI does ([#281](https://github.com/un-ts/prettier/issues/281)).

Thanks for the tip! The same issue is present with `prettier-plugin-sql`
